server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: trade-service
        uri: lb://trade-service
        predicates:
        - Path=/trade/**
        filters:
        - RewritePath=/trade/(?<path>.*), /$\{path}
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/account/**
        filters:
        - RewritePath=/account/(?<path>.*), /$\{path}